### ISSUE TITLE
Is it possible to link to a specific day for sharing?

### ISSUE THREAD

**Issue by sheldonhull** [brettmstevens7/100-days-of-code-site#1]
I'm assuming this isn't possible as I'm guessing the individual days aren't able to loaded directly from an external link, but as I'm not a React dev wanted to double check.

Would like to tweet the "day" summary similar to something like this?

![image](https://user-images.githubusercontent.com/3526320/88153173-a9c03600-cbca-11ea-97d0-2f5251778c3a.png)

I modified my fork to make sure and give you credit for such a great job. Thanks for sharing this!

**Comment by brettmstevens7** [comment]
Hey @sheldonhull thanks for the feedback! I added a new view for each entry. [Here's a quick demo](https://www.loom.com/share/da1cb9dc4fb5464b8e52bf906bfd6918).

[Here's the commit](https://github.com/brettmstevens7/100-days-of-code-site/commit/545f74bf707e6e1c0286d4455f91249eca1dc60d).

**Comment by sheldonhull** [comment]
Super cool! Thank you for this!
