### ISSUE TITLE
adding a share button with defined output for twitter

### ISSUE THREAD

**Issue by sheldonhull** [brettmstevens7/100-days-of-code-site#2]
Any tip on how I might get started with a "share" button that I could define in a script block?

I want to tweet the progress and thinking it would be great to open the page and tweak the link, url and excerpt i defined front the front matter. I know that's not the scope for this, but any tip would be appreciated.

The output might look like:

```
<title> <#tag1> <#tag2>
<trimmed excerpt>
<url>
```

With the changes you made to support per page, i think it's really helpful, and would be nice to define a tweet output from a button. I can investigate on my own, but again not a react dev, so hoping it's something you can point me in the right direction on. 

Cheers!

**Comment by brettmstevens7** [comment]
@sheldonhull [Here you go](https://github.com/brettmstevens7/100-days-of-code-site/commit/89ac4820c2ec8169671947b9cf1e491e8c7a78a7). Make sure you refetch from upstream and run `yarn`.

**Comment by sheldonhull** [comment]
https://www.sheldonhull.com/ live! i need to do a little learning on gatsby, so flexible. Right now I've been mixed on doing it on my own "microblog" and your much cleaner page. 

Gatsby is flexible I could could just feed it my other repos markdown file and render the same content in two places. Pretty awesome! 

Thanks again for this!

**Comment by brettmstevens7** [comment]
Hmm. I haven't tried it, but you might be able retrieve the markdown from your repo using the GitHub Graphql API, [like this](https://stackoverflow.com/questions/46248607/how-to-get-readme-md-from-github-graphql-api/46254836). 

Then you have two options...

You can fetch the data using the `gatsby-source-graphql` plugin in your `gatsby-config.js` file:

```javascript
{
    resolve: "gatsby-source-graphql",
    options: {
        typeName: "github",
        fieldName: "github",
        url: "https://graphql.github.com",
        headers: {
            // Learn about environment variables: https://gatsby.dev/env-vars
            Authorization: `Bearer ${process.env.GITHUB_API_KEY}`
        }
        // refetchInterval: 60
    }
}
```

Or, if you want to set up pages from markdown, you can fetch that data at build time with something like this in your Gatsby node file:

```javascript
exports.sourceNodes = async ({ actions: { createNode }, createContentDigest }) => {
    // get data from GitHub API at build time
    let endpoint = "graphql.github.com";
    const result = await fetch(endpoint, {
        headers: { Authorization: process.env.GITHUB_API_KEY }
    });
    const json = await result.json();
    createNode({
        items: json.items,
        id: "markdown",
        parent: null,
        children: [],
        internal: {
            type: "markdown",
            contentDigest: createContentDigest(json)
        }
    });
};
```
